### PR TITLE
[BUG]: npe exception after valid selection

### PR DESCRIPTION
**Pull request by toranb**
A follow up to the bug @jamesarosen found recently

### CODE REVIEW

**Comment by jamesarosen** [comment]
Hmm. I see passing tests but no new code. That suggests I'm doing something wrong in my subclass.

**Comment by jamesarosen** [comment]
+1 :)

**Comment by toranb** [comment]
@jamesarosen after months of inactivity and other OSS taking priority I decided to declare this addon as "no longer actively maintained" :(

Late last year ember-power-select was released and handles all the issues currently open here (in a much more elegant way). I've migrated from this addon to power-select and haven't looked back even myself.

**Comment by jamesarosen** [comment]
I already have a story to switch to ember-power-select :)

**Comment by toranb** [comment]
good news! sorry this project failed you dude!

**Comment by jamesarosen** [comment]
Not failed. Bridged the gap!

**Pull request closed without merging**
