### PR TITLE
Fix issue with indexing out of range when change characters inside input

### PR DESCRIPTION
**Pull request by joe-l-bright**
Please take a look at the pull request that is fixing out of range errors when changing option and trying to arrow up and down.  I also cleaned up a few things and fixed error prone lines.  There are a couple missing test for what appeared to be added later in development. Not harping on that, just mentioning that we may have a couple more defects to clean up later on.  We can wait for cases to show up :)

### CODE REVIEW

**Comment by toranb** [comment]
Wow this is an impressive refactor ! nice work @joe-l-bright 

let me look it over in depth tonight and give any feedback/merge it :)

**Comment by joe-l-bright** [comment]
Thanks T-bizzness :)

**Comment by stravid** [comment]
Nice improvements, I like your use of constants!

@toranb I will wait until this is merged before I rebase and proceed with #16. Either way it would be great to hear your favourite option regarding clearing the input!

**Comment by joe-l-bright** [comment]
@toranb I also added in the logic to maintain visibility of the highlighted item.  Previously if you arrow'd down, it would go below the client's height into its buffered scroll height.  It will now keep the item in view.  Scrolling into view is supported accross major browsers, but there is an update that we can make using options in the future when everyone catches up :)

**Comment by toranb** [comment]
Again @joe-l-bright I can't thank you enough for the polish on this pull request! Great work my friend!

**Comment by toranb** [comment]
I just did a publish to npm so look for 0.2.0 

let me know if you find anything else!

@stravid I've merged this so rebase when you have time good sir :)

**Comment by joe-l-bright** [comment]
Thanks @toranb

**Pull request merged**
