### PR TITLE
add hideWhenNoSuggestions option

### PR DESCRIPTION
**Pull request by kagemusha**
I wanted to emulate Evernote tags behavior where the suggestions dropdown disappears if no suggestions.  This PR implements that behavior and allows it to be configured.

If you like the feature, I will add tests and documentation to the PR.

### CODE REVIEW

**Comment by toranb** [comment]
Totally love this feature! Thanks for making it configurable also (a very nice to have for sure). Would you mind adding some test coverage to document this/etc ? Thanks !!!!

**Comment by kagemusha** [comment]
@toranb Done!  Let me know if need changes.

**Comment by toranb** [comment]
Awesome! I just published the beta 2 on npm so you can get at this today :)

```
npm install ember-cli-auto-complete@1.0.0-beta.2
```

**Comment by kagemusha** [comment]
Great!  And thanks for the add-on!  Was exactly what i needed for an Ember
tutorial app https://github.com/kagemusha/crambear i'm doing.

**Comment by toranb** [comment]
Wow! Glad to know this addon was so darn helpful :)

**Pull request merged**
